Adds functionality of Listing notes
JessicaLim8/NoteTaker pull request #17
Opened 2019-02-10 19:11 UTC by JessicaLim8

## Adds ability to list notes

### New functions
Allows for lists to be displayed on console via `note list <filename>` or using the `-l` or `--list` flag with existing commands. Closes issue #

#### Note List command

- Will list all the elements within the called filename
- If the list doesn't exist, it will be made
- If no list is included, the default list will be displayed

#### Note List features
- Will display the title, coloured by property
- Will display each element in the appropriate colour
- Elements are displayed with either checkmarks/crosses if they are of checkbox type, or points, if they are dot-jot notes (according to the filename's properties
- If the element is empty, it will not be displayed

#### Listing flags

- If `-l` or `--list` is flagged in any command, after the command is completed, the altered list is displayed
- Default of `-l` is false (will not list elements unless flag is present)
- If flag is pulled with conjunction with `note list` i. e. `note list -f <listname> -l`, it will only list once

2019-02-10 20:24 UTC, JonathanGin52 requested changes
Review hound's comments

2019-02-10 21:40 UTC, JessicaLim8 commented
Made the appropriate changes to address formatting issues

2019-02-10 23:41 UTC, JonathanGin52 commented on commands/list.js
> +    } else if (entries[i].checked === true) {
Remove redundant `=== true`

2019-02-10 23:43 UTC, JonathanGin52 commented on commands/list.js
> +const color = require('colors');
Redundant import

2019-02-10 23:43 UTC, JonathanGin52 commented on commands/list.js
> +  const { title, titleColour, colour, type, entries } = file;
combine line 6 and line 7 since file isn't being used anywhere else

2019-02-10 23:45 UTC, JonathanGin52 commented on commands/list.js
> +  if (entries.length === 0) {
Could be replaced by `if (!entries.length)` because 0 is falsy. This way can be kept for clarity

2019-02-11 04:38 UTC, JonathanGin52 approved these changes
Looks good

2019-02-11 04:38 UTC, merged